baseURL = 'https://eowiz.github.io/'
languageCode = 'ja-JP'
defaultContentLanguage = 'ja'
title = 'a.k.a.'
theme = "PaperMod"

[params]
  ShowShareButtons = true
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true